= SALT Proposal Data Model
:sectnums:
:icons: font
:toc: left
:iso: http://en.wikipedia.org/wiki/ISO_8601[ISO 8601 datetime string]
:phase1: (phase 1)
:phase2: (phase 2)
:phase12: (phase 1 and 2)

This document outlines the data model for SALT proposals. While it is based on the current proposal schema, it makes various changes.

== Proposal

A proposal is a request for observations to be taken. It is limited to a single semester, although in the case of a phase 1 proposal it may apply for time in multiple semesters.

NOTE: Contrary to the current schema, this means that a completely new phase 2 proposal must be submitted for a new semester.

A phase 1 proposal includes

* general information
* partners
* investigators
* targets
* observations
* instrument configurations

A phase 2 proposal includes

* general information
* investigators
* targets
* instrument configurations
* blocks
* pools

All of these are explained in detail in the sections below.

=== General information {phase12}

==== Proposal code {phase12}

The proposal code identifies a proposal across submissions and semesters; if two proposals have the same proposal code, they refer to the same observing programme. A proposal code is of the form _YYYY-S-TYPE-NUMBER_, where _YYYY_ is the year, _S_ the semester (i.e. 1 or 2), _TYPE_ is a type identifier (see <<#proposal_type,proposal types>>) and _NUMBER_ is a running number. Examples would be 2020-1-SCI-042 or 2021-2-DDT-006.

[#proposal_type]
==== Proposal type {phase12}

The available proposal types are listed in the table below, together with the corresponding type identifiers used in proposal codes.

[%header,#table_proposal_types]
.Proposal types and identifiers
|===
| Proposal Type | Description | Type identifier | Phases
| Science | "Normal" science proposal | SCI | 1 and 2
| Multisemester | Proposal for an observation program which is intended to last for more than one semester | MLT | 1 and 2
| Large Science Program | Proposal requesting more than 150 hours of observing time, which can be spread over six semesters | LSP | 1 and 2
| Director's Discretionary Time | Proposal with time allocated outside the normal TAC process. Contrary to other proposal types, no investigator has to belong to a SALT partner | DDT | 2 only
| Gravitational Wave Event | Follow-up of a gravitational wave event | GWE | 2 only
| Science Verification | Science verification proposal | SVP | 2 only
| Commissioning | Commissioning proposal | COM | 2 only
| OPTICON | Proposal which has been allocated time by OPTICON | OPT | 2 only
|===

The last column is explained in the <<#phase,Phase section>>.

==== Title {phase12}

The proposal title.

==== Abstract {phase12}

The proposal abstract.

[#period]
==== Period {phase12}

The period for which the proposal is submitted. In case of a Phase 1 proposal this is the period of the call for proposals. A period consists of a year and a semester, and is usually written as _YYYY-S_ with the year _YYYY_ and semester _S_. The semester can be either 1 (from May to October) or 2 (from November to April of the following year). See the following table for examples.

[%header]
.Examples of periods
|===
| Period | Date range
| 2020-1 | 1 May 2020 -- 31 October 2020
| 2020-2 | 1 November 2020 - 30 April 2021
| 2021-1 | 1 May 2021 -- 31 October 2021
| 2021-2 | 1 November 2021 - 30 April 2022
|===

NOTE: The term _period_ has been borrowed from ESO. The term _semester_ is used for it elsewhere, but this has the slightly annoying consequence that a semester contains a semester.

[#phase]
==== Phase {phase12}
The proposal phase, which can be either 1 or 2. Phase 1 proposals submitted in response to a call for proposals and request observing time as part of the normal TAC process. They mainly contain the scientific justification, the time requests, the targets, the investigators and some basic instrument configuration information.

A phase 2 proposal contains all the details required for carrying out the observations of the proposal.

While usually both a phase 1 and (assuming time is granted) a phase 2 proposal need to be submitted, proposals outside the normal TAC process only require a phase 2 submission. See the table in the <<#proposal_type,Proposal Type section>> for details.

==== Time requests {phase1}

A time request includes

* the amount of requested time
* the <<#period,period>> for which the time is requested
* the minimum useful time
* optionally a comment

A proposal may have multiple time requests, but only one request per period. One of the time requests should be for the proposal period (i.e. the period of the call for proposals in response to which the proposal is submitted), and no time request should be for a period earlier than the proposal period.

==== Scientific justification {phase12}

A pdf for providing scientific background and justification, as well as illustrating the technical feasibility of the planned observations. This should be created from a LaTeX or Word template (which may depend on the proposal type). However, this is not enforced programmatically.

NOTE: At the moment, the use of the correct template _is_ checked. But this might be more pain than gain.

The proposal does not include the actual pdf, but a URI for it. This URI must have been issued by SALT. In other words, the pdf must have been uploaded prior to the proposal submission.

==== Target of Opportunity {phase1}

A flag indicating whether the proposal includes target of opportunity observations.

==== Time Critical {phase1}

A flag indicating whether the proposal includes observations which are time critical.

==== Priority 4 {phase1}

A flag indicating whether this is a proposal which requests priority 4 time only.

==== Related theses {phase1}

Student theses which would use data for this proposal. For each thesis the following details should be included,

* the student (who must be an investigator for the proposal)
* the type of degree (Masters or PhD)
* the expected year of completion
* the relevance of the data for the thesis

The relevance of the data needs to be included only if the proposal requests time from the South African TAC.

==== External funding {phase1}

A free-form string naming any non-SALT funding source(s). This is for the benefit of the PI only.

==== Previous proposals {phase1}

A list of the PI's proposals from the previous four periods. Each proposal includes

* the proposal code
* a comment on the proposal status

==== Publications {phase1}

A list of publications by any of the investigators which are of relevance for this proposal. These are given as a list of bibcodes.

NOTE: This is new (and borrowed from ESO).

==== Summary for the general public

A short summary which may be shared with the general public.

==== Allow details to be displayed

A flag for allowing that the proposal title, PI and summary are shown during to the general public during an observation, for example by tweeting them.

== Partner {phase1}

Partner related details for the proposal.

=== Partner code

A unique code identifier for the partner, as given in the following table.

[%header]
.Partner codes
|===
| Partner code | Partner
| AMNH | American Museum of Natural History
| CMU | Carnegie Mellon University
| DC | Dartmouth College
| DUR | Durham University
| GU | Georg-August-Universität Göttingen
| HET | Hobby Eberly Telescope Board
| IUCAA | Inter-University Centre for Astronomy & Astrophysics
| POL | Poland
| RSA | South Africa
| RU | Rutgers University
| UC | University of Canterbury
| UKSC | UK SALT Consortium
| UNC | University of North Carolina - Chapel Hill
| UW | University of Wisconsin-Madison
|===

=== Requested time share

The amount of time requested from the partner, as a percentage. The requested time shares must add up to 100 %.

=== Role of investigators

The role the investigators (including students) of this proposal. This is only required for LSP proposals requesting time from the South African TAC.

== Investigator {phase12}

At the moment, the proposal contains contact details as well as the partner affiliation. This more or less by implication means that users cannot easily update their contact details. Also, including these details in a proposal implies duplication of information.

For these reasons the data model does not include contact details or partner affiliations any longer.

An investigator thus is just a unique identifier. This must be the identifier for the user in the authentication service.

NOTE: At the moment this might be the primary key in the `PiptUser` table of the SDB. However, the authentication system might be overhauled.

== Target {phase12}

A target is an object to be observed as part of the proposal.

NOTE: Targets can have no finding charts any longer. Also, the flag distinguishing between mandatory and optional targets exists no longer; there is a respective flag for observations now.

=== Target name

The name of the target. This must be unique within a proposal.

=== Target code

A string identifying this target. The target code should be unique within a proposal and should not change across submissions. However, different proposals may have targets with the same code; global uniqueness is not guaranteed.

=== Version

Version of this target (information). A particular combination of target code and version can only be submitted once. In other words, if you need to resubmit a target, you need to change the version first.

NOTE: This is a new requirement and is motivated by a similar requirement for blocks.

=== Target type

The target type, as a standard name defined by the http://simbad.u-strasbg.fr/simbad/sim-display?data=otypes&option=display+numeric+codes[SIMBAD object classification]. Examples are "AbsLineSystem", "Candidate_LMXB" and "Planet?".

=== Target ephemerides

The target ephemeris. This may be either of coordinates, a Horizons identifier or a dummy target flag.

==== Coordinates

The coordinates include

* the right ascension, as an angle between 0 and 360 degrees
* the declination, as an angle between -90 and 90 degrees
* the equinox, as a float

For targets with a high proper motion the following may be added:

* the proper motion for the right ascension (in arcseconds per year)
* the proper motion for the declination (in arcseconds per year)
* the epoch as an {iso}.

==== Horizons identifier

An identifier understood by https://ssd.jpl.nasa.gov/horizons.cgi[NASA JPL's Horizons service]. This may be an object name (such as "Ubuntu") or a designation (such as "2005 EW302").

NOTE: There used to be an output interval as well. However, this seems unnecessary.

==== Dummy target

A flag indicating that the target is a dummy target only.

=== Magnitude range

The magnitude range includes

* the minimum (brightest) magnitude
* the maximum (faintest) magnitude
* the bandpass for the magnitude range, which must be any of U, B, V, R or I.

=== Phase

In order to easily define observing windows details about a variable target's phase may be provided.

==== Time of phase zero

A datetime at which the target's phase is 0. This should be an {iso}.

==== Time base

The timebase to use. This may be Julian Day, Heliocentric Julian Day or Barycentric Julian Day.

==== Period

The period of variability, in days.

NOTE: There used to be rate of change of the period as well. This has rarely (if ever) been used and has been dropped.

== Observation {phase1}

=== Target

A reference to a target. The target must exist in the proposal.

=== Observing time

The observing time for all visits of the observation combined. Thias includes acquisition and overhead times. The time is given in seconds.

=== Visits

The number of visits, i.e. how often the observation is to be carried out.

=== Maximum lunar phase

The maximum lunar phase at which this observation can be done (see ???).

=== Ranking

A measure of the importance of this observation relative to the other observations in the proposal. The following values are possible.

[%header]
.Ranking values
|===
| Ranking
| High
| Low
| Medium
|===

=== Optional flag

A flag indicating that the observation is optional, i.e. belongs to a pool of observations out of which only a subset needs to be observed.

== Instrument configuration {phase1}

An instrument configuration for phase 1 contains a name, simulations and details for one instrument (<<#salticam_p1,Salticam>>, <<#rss_p1,RSS>>, <<#hrs_p1,HRS>> or <<#bvit_p1,BVIT>>).

=== Name

A name for the configuration. This must be unique within the proposal.

=== Simulations

A list of simulations. Each simulation includes a URI and a comment.

==== File URI

URI for the simulation file. This file must be viewable in the simulation tool for the instrument used by this configuration. The URI must have been assigned by SALT. In other words, the simulation file must have been uploaded to SALT before the proposal is submitted.

==== Comment

An optional comment regarding the simulation.

[#salticam_p1]
=== Salticam

==== Detector mode

The detector mode. This must be any of the available detector modes for Salticam (see ???).

==== Filters

A list of filters. Each filter must be any of the available filters for Salticam (see ???).

[#rss_p1]
=== RSS

NOTE: The slit type is not included any longer.

A name for the configuration. This must be unique within the proposal.

==== Detector mode

The detector mode. This must be any of the available detector modes for RSS (see ???).

==== RSS mode

The mode in which RSS is operated. This can be any of the following.

[%header]
.RSS modes
|===
| Mode mode
| Fabry-Perot
| Fabry-Perot polarimetry
| Imaging
| Imaging polarimetry
| MOS
| MOS polarimetry
| Spectropolarimetry
| Spectroscopy
|===

==== Polarimetry

The type of polarimetry. Any of the following types are allowed.

[%header]
.Polarimetry types
|===
| Polarimetry type
| All Stokes
| Circular
| Circular Hi
| Linear
| Linear Hi
| User Defined
|===

The polarimetry type is only relevant if a polarimetric RSS mode has been chosen.

==== Grating

The grating to use for a spectroscopic or spectropolarimetric setup. Any of the available RSS gratings (see ???) can be chosen.

[#hrs_p1]
=== HRS

==== Mode

The HRS mode, which can be any of the available HRS modes (see ???).

[#bvit_p1]
=== BVIT

==== Filter

The filter, which can be any of the available BVIT filters (see ???).

== Pool {phase2}

A pool is a group of blocks, and every block must be a member of exactly one pool. A pool rule describes how to observe the pool blocks.

In most cases the PI has no need to group blocks. Such ungrouped blocks are collected in a default pool.

=== Blocks

A list of blocks. The list items are the actual blocks, not references.

=== Pool rule

A rule describing how to observe the pool blocks. This a string which conforms to the SALT proposal DSL. Any parameters must be included in the rule.For example, if a subset of the blocks are to be observed and 3000 seconds of priority 1 and 4000 seconds of priority 2 time should be spent on the pool, the rule might look as follows.

====
OBSERVE ANY BLOCKS FOR 3000 SECONDS WITH PRIORITY 1 AND FOR 4000 SECONDS WITH PRIORITY 2.
====

The rule for the default pool might look as follows.

====
OBSERVE ALL BLOCKS
====

Finally, the rule for a pool aimed at monitoring a target might look as follows.

====
OBSERVE ALL BLOCKS WITH A WAITING TIME OF 5 DAYS
====

NOTE: The precise wording will probably change, as the DSL has not been defined yet.

[glossary]
== Glossary

[glossary]
Bibcode:: https://en.wikipedia.org/wiki/Bibcode[Bibliographic reference code]
BVIT:: Berkeley Visible Image Tube
DSL:: Domain-specific language
ESO:: European Southern Observatory
HRS:: High Resolution Spectrograph
LSP:: Large Science Program
PI:: Principal Investigator
RSS:: Robert Stobie Spectrograph
SALT:: Southern African Large Telescope
SDB:: SALT Science Database
SIMBAD:: Astronomical database of objects beyond the Solar System,  maintained by the Centre de données astronomiques de Strasbourg (CDS)
TAC:: time allocation committee
